### ISSUE TITLE
graph突然停止&&panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by hsqlu** [open-falcon/graph#18]
刚刚开始试试open-falcon，安装还顺利 正在熟悉，发现graph两次自动down掉了。下面的报错是什么原因呢？

2016/03/24 23:24:18 cfg.go:90: g.ParseConfig ok, file cfg.json
2016/03/24 23:24:18 db.go:26: g.InitDB ok
2016/03/24 23:24:18 rrdtool.go:55: rrdtool.Start ok
2016/03/24 23:24:18 index.go:15: index.Start ok
2016/03/24 23:24:18 main.go:20: 15851 register signal notify
2016/03/24 23:24:18 rpc.go:54: rpc.Start ok, listening on 0.0.0.0:6070
2016/03/24 23:24:18 http.go:96: http listening 0.0.0.0:6071
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 14 [running]:
panic(0x90f2e0, 0xc820315e30)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/open-falcon/rrdlite.(_Updater).update(0xc820036de8, 0xc82031c240, 0x6, 0x8, 0x0, 0x0)
    /workspace/golang/src/github.com/open-falcon/rrdlite/rrd_c.go:70 +0x100
github.com/open-falcon/rrdlite.(_Updater).Update(0xc820036de8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /workspace/golang/src/github.com/open-falcon/rrdlite/rrd.go:130 +0x27f
github.com/open-falcon/graph/rrdtool.update(0xc8202ec4b0, 0x45, 0xc82031a210, 0x6, 0x6, 0x0, 0x0)
    /workspace/golang/src/github.com/open-falcon/graph/rrdtool/rrdtool.go:117 +0x45e
github.com/open-falcon/graph/rrdtool.flushrrd(0xc8202ec4b0, 0x45, 0xc82031a210, 0x6, 0x6, 0x0, 0x0)
    /workspace/golang/src/github.com/open-falcon/graph/rrdtool/rrdtool.go:142 +0x1a2
github.com/open-falcon/graph/rrdtool.ioWorker()
    /workspace/golang/src/github.com/open-falcon/graph/rrdtool/sync_disk.go:95 +0x38f
created by github.com/open-falcon/graph/rrdtool.Start
    /workspace/golang/src/github.com/open-falcon/graph/rrdtool/rrdtool.go:54 +0x24f

**Comment by hsqlu** [comment]
Repeated with issue #17
